### ISSUE TITLE
Update website for Fantom launch

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-website#22]

**Comment by Olafkuusik** [comment]
Changes required to the website are:
1. Navigation menu changes: 
- Sers link is moved under community, 
- Governance is added under community
![image](https://user-images.githubusercontent.com/22838368/152778642-4974c8b4-e3c6-4961-b54c-5986f1d34aab.png)


2. When scrolled down -> sticky header call to action button "LAUNCH APP" color changes to #288195 (currently it is #FFFFFF)

![image](https://user-images.githubusercontent.com/22838368/152778674-c03f244a-a266-4081-bb74-b3faf0f8e620.png)


3. Heading "Integrated with" is replaced with: "Fix your future yield"
4. Added paragraph "Tempus lets you fix your yield on many networks. Choose your preferred network below to get started."
5. Removed protocol icons, instead added 2 cards (Ethereum Mainnet) and (Fantom Opera), showing only protocols in use on that particular network.
6. In the cards we display the highest APY value on the network as a "Up to xx.xx%"
7. Invest now call to action in the cards leads to the app dashboard and with that network already selected from which card the user started journey. (Ethereum Mainnet "Invest now" leads to app with Ethereum selected as network and Fantom Opera "Invest now" will lead to app with Fantom network as the preselected network).
PC view:
![image](https://user-images.githubusercontent.com/22838368/152779401-45acb952-676d-4887-a5f6-1892fa41280b.png)
and mobile view: 
![image](https://user-images.githubusercontent.com/22838368/152779453-651da91e-73f8-4c6f-8441-3b71277b548d.png)
