### ISSUE TITLE
Enhance mobile menu dropdown for nested pages 

### ISSUE THREAD

**Issue by RTP2016** [tempus-finance/tempus-website#33]

**Comment by Olafkuusik** [comment]
Menu changes:
PC:
![image](https://user-images.githubusercontent.com/22838368/154661750-4dfd31c2-eda8-47aa-8acd-d8f61408bf83.png)
Mobile:
![image](https://user-images.githubusercontent.com/22838368/154661862-07344666-5514-4505-9e42-6238c8c9735f.png)

When About is clicked:
![image](https://user-images.githubusercontent.com/22838368/154661966-ff01cd7c-9cf1-46d6-8d1e-7145b4a40881.png)

When community is clicked: 
![image](https://user-images.githubusercontent.com/22838368/154661912-3609e197-99db-4ed6-a413-ec5646d4f330.png)

Back to home is solved via clicking on logo.
Clicking on 'Back' will return the user to previous level of menu.
Clicking on 'X' will close the menu, if the user re-opens the menu it will show the default start view, not where the user left off.
When user is on a subpage then the navigation menu will still start from the default start position.
![image](https://user-images.githubusercontent.com/22838368/154662245-bb56a60b-a8d8-40a9-87d4-5f1366dec87b.png)
Nice to have feature:
If the user is currently on a subpage which is available on the menu then that link should have different style, in this case: text-weight changed to bold. (Example: user is on Team page -> opens navigation menu -> clicks About -> Team link is in bold)
![image](https://user-images.githubusercontent.com/22838368/154662399-dfca14f8-be24-4ede-8940-9e6744894c6d.png)


Prototype: https://www.figma.com/proto/OC9hkmz1oOm3twN6iGftya/Tempus---Marketing?page-id=375%3A7679&node-id=375%3A7680&viewport=501%2C48%2C0.53&scaling=min-zoom&starting-point-node-id=375%3A7680&show-proto-sidebar=1

Figma file: Tempus project > Tempus - Marketing file > --Mobile navigation page
