### ISSUE TITLE
Can't launch Application when resolution is low

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-website#73]
**Describe the bug**
When the resolution is under 1010 pixels, we can't launch the application. There is a button App Available on Desktop, but the button is not working. When the resolution is below 1010 pixels, there are no INVEST NOW buttons on Ethereum and Fantom widgets. When the resolution is bellow 1010 pixels.

**To Reproduce**
1. Go to https://tempus.finance/
2. Select a resolution that is below 1010 pixels

**Expected behavior**
The button App Available on Desktop and INVEST NOW should link you to the main Application.

**Actual behavior**
The button App Available on Desktop is not working. There are no INVEST NOW buttons.

**Screenshots**
![Selection_008](https://user-images.githubusercontent.com/98878781/171007576-32016922-09ab-47f4-a98b-edfc62bc74b9.png)
![Selection_009](https://user-images.githubusercontent.com/98878781/171007640-05be6cb5-9159-402d-bb03-f845cd03cf40.png)

**Comment by iamvukasin** [comment]
Not relevant anymore since the website is updated.
